# Generated by Django 5.2.5 on 2025-08-12 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionCashflowPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('directly_attributable', models.BooleanField(default=True)),
                ('amortize_by_coverage_units', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('HUF', 'Hungarian Forint'), ('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound')], default='HUF', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremiumPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('SINGLE', 'Single'), ('ANNUAL', 'Annual'), ('SEMI_ANNUAL', 'Semi-Annual'), ('QUARTERLY', 'Quarterly'), ('MONTHLY', 'Monthly')], default='ANNUAL', max_length=12)),
                ('is_level', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('measurement_model', models.CharField(choices=[('GMM', 'General Measurement Model'), ('VFA', 'Variable Fee Approach')], default='GMM', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('HUF', 'Hungarian Forint'), ('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound')], default='HUF', max_length=3)),
                ('cohort_year', models.PositiveIntegerField()),
                ('coverage_term_years', models.PositiveIntegerField()),
                ('premium_term_years', models.PositiveIntegerField()),
                ('policy_count', models.PositiveIntegerField(default=0)),
                ('sum_assured', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('written_premium', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('acq_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='contracts.acquisitioncashflowpolicy')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='contracts.portfolio')),
                ('premium_pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='contracts.premiumpattern')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='contracts.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'product', 'cohort_year', 'code'), name='uniq_group_per_portfolio_product_year_code')],
            },
        ),
    ]
