# Generated by Django 5.2.5 on 2025-08-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_contractgroup_uniq_group_per_portfolio_product_year_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractgroup',
            options={'ordering': ('portfolio', 'product', 'cohort_year', 'code')},
        ),
        migrations.AddConstraint(
            model_name='contractgroup',
            constraint=models.UniqueConstraint(fields=('portfolio', 'product', 'cohort_year', 'code'), name='uniq_group_per_portfolio_product_year_code'),
        ),
        migrations.AddConstraint(
            model_name='contractgroup',
            constraint=models.CheckConstraint(condition=models.Q(('premium_term_years__lte', models.F('coverage_term_years'))), name='chk_premium_term_le_coverage_term'),
        ),
    ]
