# Generated by Django 5.2.5 on 2025-08-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('curve_type', models.CharField(choices=[('LOCKED_IN', 'Locked-in (at initial recognition)'), ('CURRENT', 'Current (measurement-date)')], default='CURRENT', max_length=10)),
                ('compounding', models.CharField(choices=[('ANNUAL', 'Annual')], default='ANNUAL', max_length=10)),
                ('rates', models.JSONField(help_text='List of per-period spot rates as decimals, e.g. [0.03, 0.031, 0.032].')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAdjustmentParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('TOY_FACTOR', 'Toy factor × expected claims'), ('CONFIDENCE_LEVEL', 'Confidence level method'), ('COST_OF_CAPITAL', 'Cost of capital method')], default='TOY_FACTOR', max_length=20)),
                ('factor', models.DecimalField(decimal_places=4, default=0.1, help_text='For TOY_FACTOR, RA per period = factor × expected claims.', max_digits=6)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
